; EngineFlags indexes (see engine/engine_flags.asm)
	const_def
; wPokegearFlags
	const ENGINE_RADIO_CARD
	const ENGINE_MAP_CARD
	const ENGINE_PHONE_CARD
	const ENGINE_EXPN_CARD
	const ENGINE_POKEGEAR
; wDayCareMan
	const ENGINE_DAY_CARE_MAN_HAS_EGG
	const ENGINE_DAY_CARE_MAN_HAS_MON
; wDayCareLady
	const ENGINE_DAY_CARE_LADY_HAS_MON
; wMomSavingMoney
	const ENGINE_MOM_SAVING_MONEY
	const ENGINE_MOM_ACTIVE
; wUnusedTwoDayTimerOn
	const ENGINE_0A
; wStatusFlags
	const ENGINE_POKEDEX
	const ENGINE_UNOWN_DEX
	const ENGINE_CAUGHT_POKERUS
	const ENGINE_ROCKET_SIGNAL_ON_CH20
	const ENGINE_CREDITS_SKIP
	const ENGINE_MAIN_MENU_MOBILE_CHOICES ; 10
; wStatusFlags2
	const ENGINE_BUG_CONTEST_TIMER
	const ENGINE_SAFARI_ZONE
	const ENGINE_ROCKETS_IN_RADIO_TOWER
	const ENGINE_BIKE_SHOP_CALL_ENABLED
	const ENGINE_15
	const ENGINE_REACHED_GOLDENROD
	const ENGINE_ROCKETS_IN_MAHOGANY
; wBikeFlags
	const ENGINE_STRENGTH_ACTIVE
	const ENGINE_ALWAYS_ON_BIKE
	const ENGINE_DOWNHILL
; wJohtoBadges
	const ENGINE_WAVEBADGE
	const ENGINE_SPOOKYBADGE
	const ENGINE_INSECTBADGE
	const ENGINE_TOXICBADGE
	const ENGINE_GARNISHBADGE
	const ENGINE_BASICBADGE ; 20
	const ENGINE_JETBADGE
	const ENGINE_LEGENDBADGE
; wKantoBadges
	const ENGINE_BOULDERBADGE
	const ENGINE_CASCADEBADGE
	const ENGINE_THUNDERBADGE
	const ENGINE_RAINBOWBADGE
	const ENGINE_SOULBADGE
	const ENGINE_MARSHBADGE
	const ENGINE_VOLCANOBADGE
	const ENGINE_EARTHBADGE
; wUnlockedUnowns
	const ENGINE_UNLOCKED_UNOWNS_A_TO_K
	const ENGINE_UNLOCKED_UNOWNS_L_TO_R
	const ENGINE_UNLOCKED_UNOWNS_S_TO_W
	const ENGINE_UNLOCKED_UNOWNS_X_TO_Z
	const ENGINE_UNLOCKED_UNOWNS_UNUSED_4
	const ENGINE_UNLOCKED_UNOWNS_UNUSED_5 ; 30
	const ENGINE_UNLOCKED_UNOWNS_UNUSED_6
	const ENGINE_UNLOCKED_UNOWNS_UNUSED_7
; wVisitedSpawns
	const ENGINE_FLYPOINT_PLAYERS_HOUSE
	const ENGINE_FLYPOINT_VIRIDIAN_POKECENTER
	const ENGINE_FLYPOINT_HUMILAU
	const ENGINE_FLYPOINT_LACUNOSA
	const ENGINE_FLYPOINT_UNDELLA
	const ENGINE_FLYPOINT_LENTIMAS
	const ENGINE_FLYPOINT_NIMBASA
	const ENGINE_FLYPOINT_CASTELIA
	const ENGINE_FLYPOINT_ASPERTIA
	const ENGINE_FLYPOINT_FLOCCESY
	const ENGINE_FLYPOINT_VIRBANK
	const ENGINE_FLYPOINT_NACRENE
	const ENGINE_FLYPOINT_STRIATON
	const ENGINE_FLYPOINT_ACCUMULA
	const ENGINE_FLYPOINT_NUVEMA
	const ENGINE_FLYPOINT_DRIFTVEIL
	const ENGINE_FLYPOINT_MISTRALTON
	const ENGINE_FLYPOINT_OPELUCID
	const ENGINE_FLYPOINT_ICIRRUS
	const ENGINE_FLYPOINT_PKMN_LEAGUE
	const ENGINE_FLYPOINT_UNUSED
; wLuckyNumberShowFlag
	const ENGINE_LUCKY_NUMBER_SHOW
; wStatusFlags2
	const ENGINE_4F
; wDailyFlags1
	const ENGINE_KURT_MAKING_BALLS ; 50!
	const ENGINE_DAILY_BUG_CONTEST
	const ENGINE_FISH_SWARM
	const ENGINE_GOT_MILK_TODAY
	const ENGINE_ALL_FRUIT_TREES
	const ENGINE_GOT_CASTELIACONE_TODAY
	const ENGINE_BALL_MANIAC
	const ENGINE_ROCK_COLLECTOR
; wDailyFlags2
	const ENGINE_BATTLE_HOUSE ; !
	const ENGINE_UNION_CAVE_LAPRAS ; !
	const ENGINE_CASTELIA_MASSAGE
	const ENGINE_GOLDENROD_DEPT_STORE_TM27_RETURN ; !
	const ENGINE_BERRY_MAN
	const ENGINE_INDIGO_PLATEAU_RIVAL_FIGHT ; !
	const ENGINE_DAILY_MOVE_TUTOR ; !
	const ENGINE_BUENAS_PASSWORD
; wSwarmFlags
	const ENGINE_BUENAS_PASSWORD_2 ; 60
	const ENGINE_GOLDENROD_DEPT_STORE_SALE_IS_ON
; wGameTimerPause
	const ENGINE_62
; wPlayerGender
	const ENGINE_PLAYER_IS_FEMALE
; wCelebiEvent
	const ENGINE_FOREST_IS_RESTLESS
; wDailyRematchFlags
	const ENGINE_DAN
	const ENGINE_JEWEL
	const ENGINE_FREDDY
	const ENGINE_ERIC
	const ENGINE_LACEY
	const ENGINE_SOPHIE
	const ENGINE_ARIANA
	const ENGINE_CARLA
	const ENGINE_CLARISSA
	const ENGINE_JENNY
	const ENGINE_MARCO
	const ENGINE_PARKER
	const ENGINE_DEAN
	const ENGINE_LOIS
;
	const ENGINE_ROOD
	const ENGINE_HUGH
	const ENGINE_ALDER
	const ENGINE_IRIS
	const ENGINE_CYNTHIA
	const ENGINE_CAITLIN
	const ENGINE_NATE_ROSA
	const ENGINE_HILBERT_HILDA
	
	const ENGINE_PARRY
	const ENGINE_ERIN
; wDailyPhoneItemFlags
	const ENGINE_BEVERLY_HAS_NUGGET
	const ENGINE_JOSE_HAS_STAR_PIECE
	const ENGINE_WADE_HAS_ITEM
	const ENGINE_GINA_HAS_LEAF_STONE ; 80
	const ENGINE_ALAN_HAS_FIRE_STONE
	const ENGINE_DANA_HAS_THUNDERSTONE
	const ENGINE_DEREK_HAS_NUGGET
	const ENGINE_TULLY_HAS_WATER_STONE
	const ENGINE_TIFFANY_HAS_PINK_BOW
	const ENGINE_WILTON_HAS_ITEM
; wDailyPhoneTimeOfDayFlags
	const ENGINE_DAN_READY_FOR_REMATCH
	const ENGINE_JEWEL_READY_FOR_REMATCH
	const ENGINE_FREDDY_READY_FOR_REMATCH
	const ENGINE_ERIC_READY_FOR_REMATCH
	const ENGINE_LACEY_READY_FOR_REMATCH
	const ENGINE_SOPHIE_READY_FOR_REMATCH
	const ENGINE_ARIANA_READY_FOR_REMATCH
	const ENGINE_CARLA_READY_FOR_REMATCH
	const ENGINE_CLARISSA_READY_FOR_REMATCH
	const ENGINE_JENNY_READY_FOR_REMATCH
	const ENGINE_MARCO_READY_FOR_REMATCH
	const ENGINE_PARKER_READY_FOR_REMATCH
	const ENGINE_DEAN_READY_FOR_REMATCH
	const ENGINE_LOIS_READY_FOR_REMATCH
;
	const ENGINE_ALAN_WEDNESDAY_AFTERNOON
	const ENGINE_DANA_THURSDAY_NIGHT
	const ENGINE_CHAD_FRIDAY_MORNING
	const ENGINE_TULLY_SUNDAY_NIGHT
	const ENGINE_BRENT_MONDAY_MORNING
	const ENGINE_TIFFANY_TUESDAY_AFTERNOON
	const ENGINE_VANCE_WEDNESDAY_NIGHT
	const ENGINE_WILTON_THURSDAY_MORNING
	const ENGINE_PARRY_FRIDAY_AFTERNOON
	const ENGINE_ERIN_SATURDAY_NIGHT
; wPlayerSpriteSetupFlags
	const ENGINE_KRIS_IN_CABLE_CLUB
; wSwarmFlags
	const ENGINE_DUNSPARCE_SWARM ; a0
	const ENGINE_YANMA_SWARM
NUM_ENGINE_FLAGS EQU const_value
