; IconPointers indexes (see data/icon_pointers.asm)
	const_def
	const ICON_NULL
	const ICON_SNIVY      ; 01
	const ICON_SERVINE    ; 02
	const ICON_SERPERIOR  ; 03
	const ICON_TEPIG      ; 04
	const ICON_PIGNITE    ; 05
	const ICON_EMBOAR     ; 06
	const ICON_OSHAWOTT   ; 07
	const ICON_DEWOTT     ; 08
	const ICON_SAMUROTT   ; 09
	const ICON_PATRAT     ; 0a
	const ICON_WATCHOG    ; 0b
	const ICON_PURRLOIN   ; 0c
	const ICON_LIEPARD    ; 0d
	const ICON_PIDOVE     ; 0e
	const ICON_TRANQUILL  ; 0f
	const ICON_UNFEZANT   ; 10
	const ICON_IGGLYBUFF  ; 11
	const ICON_JIGGLYPUFF ; 12
	const ICON_WIGGLYTUFF ; 13
	const ICON_AZURILL    ; 14
	const ICON_MARILL     ; 15
	const ICON_AZUMARILL  ; 16
	const ICON_SEWADDLE   ; 17
	const ICON_SWADLOON   ; 18
	const ICON_LEAVANNY   ; 19
	const ICON_VENIPEDE   ; 1a
	const ICON_WHIRLIPEDE ; 1b
	const ICON_SCOLIPEDE  ; 1c
	const ICON_LILLIPUP   ; 1d
	const ICON_HERDIER    ; 1e
	const ICON_STOUTLAND  ; 1f
	const ICON_TYMPOLE    ; 20
	const ICON_PALPITOAD  ; 21
	const ICON_SEISMITOAD ; 22
	const ICON_ZUBAT      ; 23
	const ICON_GOLBAT     ; 24
	const ICON_CROBAT     ; 25
	const ICON_WOOBAT     ; 26
	const ICON_SWOOBAT    ; 27
	const ICON_ROGGENROLA ; 28
	const ICON_BOLDORE    ; 29
	const ICON_GIGALITH   ; 2a
	const ICON_CLEFFA     ; 2b
	const ICON_CLEFAIRY   ; 2c
	const ICON_CLEFABLE   ; 2d
	const ICON_MUNNA      ; 2e
	const ICON_MUSHARNA   ; 2f
	const ICON_RUFFLET    ; 30
	const ICON_BRAVIARY   ; 31
	const ICON_VULLABY    ; 32
	const ICON_MANDIBUZZ  ; 33
	const ICON_BUDEW      ; 34
	const ICON_ROSELIA    ; 35
	const ICON_ROSERADE   ; 36
	const ICON_FOONGUS    ; 37
	const ICON_AMOONGUSS  ; 38
	const ICON_RALTS      ; 39
	const ICON_KIRLIA     ; 3a
	const ICON_GARDEVOIR  ; 3b
	const ICON_GALLADE    ; 3c
	const ICON_BLITZLE    ; 3d
	const ICON_ZEBSTRIKA  ; 3e
	const ICON_MAREEP     ; 3f
	const ICON_FLAAFFY    ; 40
	const ICON_AMPHAROS   ; 41
	const ICON_DRILBUR    ; 42
	const ICON_EXCADRILL  ; 43
	const ICON_SNUBBULL   ; 44
	const ICON_GRANBULL   ; 45
	const ICON_RIOLU      ; 46
	const ICON_LUCARIO    ; 47
	const ICON_TIMBURR    ; 48
	const ICON_GURDURR    ; 49
	const ICON_CONKELDURR ; 4a
	const ICON_ARON       ; 4b
	const ICON_LAIRON     ; 4c
	const ICON_AGGRON     ; 4d
	const ICON_ONIX       ; 4e
	const ICON_STEELIX    ; 4f
	const ICON_NOSEPASS   ; 50
	const ICON_PROBOPASS  ; 51
	const ICON_MAWILE     ; 52
	const ICON_DWEBBLE    ; 53
	const ICON_CRUSTLE    ; 54
	const ICON_DRIFLOON   ; 55
	const ICON_DRIFBLIM   ; 56
	const ICON_MEDITITE   ; 57
	const ICON_MEDICHAM   ; 58
	const ICON_HOUNDOUR   ; 59
	const ICON_HOUNDOOM   ; 5a
	const ICON_YAMASK     ; 5b
	const ICON_COFAGRIGUS ; 5c
	const ICON_GASTLY     ; 5d
	const ICON_HAUNTER    ; 5e
	const ICON_GENGAR     ; 5f
	const ICON_LITWICK    ; 60
	const ICON_LAMPENT    ; 61
	const ICON_CHANDELURE ; 62
	const ICON_COTTONEE   ; 63
	const ICON_WHIMSICOTT ; 64
	const ICON_PETILIL    ; 65
	const ICON_LILLIGANT  ; 66
	const ICON_YANMA      ; 67
	const ICON_YANMEGA    ; 68
	const ICON_SHROOMISH  ; 69
	const ICON_BRELOOM    ; 6a
	const ICON_JOLTIK     ; 6b
	const ICON_GALVANTULA ; 6c
	const ICON_SPIRITOMB  ; 6d
	const ICON_ZORUA      ; 6e
	const ICON_ZOROARK    ; 6f
	const ICON_TRUBBISH   ; 70
	const ICON_GARBODOR   ; 71
	const ICON_MAGNEMITE  ; 72
	const ICON_MAGNETON   ; 73
	const ICON_MAGNEZONE  ; 74
	const ICON_GOTHITA    ; 75
	const ICON_GOTHORITA  ; 76
	const ICON_GOTHITELLE ; 77
	const ICON_SOLOSIS    ; 78
	const ICON_DUOSION    ; 79
	const ICON_REUNICLUS  ; 7a
	const ICON_DEERLING   ; 7b
	const ICON_SAWSBUCK   ; 7c
	const ICON_KARRABLAST ; 7d
	const ICON_ESCAVALIER ; 7e
	const ICON_SHELMET    ; 7f
	const ICON_ACCELGOR   ; 80
	const ICON_FERROSEED  ; 81
	const ICON_FERROTHORN ; 82
	const ICON_BASCULIN   ; 83
	const ICON_REMORAID   ; 84
	const ICON_OCTILLERY  ; 85
	const ICON_DARUMAKA   ; 86
	const ICON_DARMANITAN ; 87
	const ICON_ELEKID     ; 88
	const ICON_ELECTABUZZ ; 89
	const ICON_ELECTIVIRE ; 8a
	const ICON_MAGBY      ; 8b
	const ICON_MAGMAR     ; 8c
	const ICON_MAGMORTAR  ; 8d
	const ICON_SANDILE    ; 8e
	const ICON_KROKOROK   ; 8f
	const ICON_KROOKODILE ; 90
	const ICON_SKORUPI    ; 91
	const ICON_DRAPION    ; 92
	const ICON_TRAPINCH   ; 93
	const ICON_VIBRAVA    ; 94
	const ICON_FLYGON     ; 95
	const ICON_SCRAGGY    ; 96
	const ICON_SCRAFTY    ; 97
	const ICON_NUMEL      ; 98
	const ICON_CAMERUPT   ; 99
	const ICON_MARACTUS   ; 9a
	const ICON_GLIGAR     ; 9b
	const ICON_GLISCOR    ; 9c
	const ICON_BALTOY     ; 9d
	const ICON_CLAYDOL    ; 9e
	const ICON_SIGILYPH   ; 9f
	const ICON_GOLETT     ; a0
	const ICON_GOLURK     ; a1
	const ICON_TIRTOUGA   ; a2
	const ICON_CARRACOSTA ; a3
	const ICON_ARCHEN     ; a4
	const ICON_ARCHEOPS   ; a5
	const ICON_FRILLISH   ; a6
	const ICON_JELLICENT  ; a7
	const ICON_EMOLGA     ; a8
	const ICON_VULPIX     ; a9
	const ICON_NINETALES  ; aa
	const ICON_DUCKLETT   ; ab
	const ICON_SWANNA     ; ac
	const ICON_SWABLU     ; ad
	const ICON_ALTARIA    ; ae
	const ICON_AUDINO     ; af
	const ICON_EEVEE      ; b0
	const ICON_VAPOREON   ; b1
	const ICON_JOLTEON    ; b2
	const ICON_FLAREON    ; b3
	const ICON_ESPEON     ; b4
	const ICON_UMBREON    ; b5
	const ICON_LEAFEON    ; b6
	const ICON_GLACEON    ; b7
	const ICON_SYLVEON    ; b8
	const ICON_CROAGUNK   ; b9
	const ICON_TOXICROAK  ; ba
	const ICON_HEATMOR    ; bb
	const ICON_DURANT     ; bc
	const ICON_KOFFING    ; bd
	const ICON_WEEZING    ; be
	const ICON_CORSOLA    ; bf
	const ICON_PINSIR     ; c0
	const ICON_HERACROSS  ; c1
	const ICON_THROH      ; c2
	const ICON_SAWK       ; c3
	const ICON_TROPIUS    ; c4
	const ICON_PAWNIARD   ; c5
	const ICON_BISHARP    ; c6
	const ICON_SKARMORY   ; c7
	const ICON_MANTYKE    ; c8
	const ICON_MANTINE    ; c9
	const ICON_AXEW       ; ca
	const ICON_FRAXURE    ; cb
	const ICON_HAXORUS    ; cc
	const ICON_BOUFFALANT ; cd
	const ICON_KLINK      ; ce
	const ICON_KLANG      ; cf
	const ICON_KLINKLANG  ; d0
	const ICON_DITTO      ; d1
	const ICON_STARYU     ; d2
	const ICON_STARMIE    ; d3
	const ICON_CUBCHOO    ; d4
	const ICON_BEARTIC    ; d5
	const ICON_VANILLITE  ; d6
	const ICON_VANILLISH  ; d7
	const ICON_VANILLUXE  ; d8
	const ICON_SNEASEL    ; d9
	const ICON_WEAVILE    ; da
	const ICON_CORPHISH   ; db
	const ICON_CRAWDAUNT  ; dc
	const ICON_SWINUB     ; dd
	const ICON_PILOSWINE  ; de
	const ICON_MAMOSWINE  ; df
	const ICON_LARVITAR   ; e0
	const ICON_PUPITAR    ; e1
	const ICON_TYRANITAR  ; e2
	const ICON_LARVESTA   ; e3
	const ICON_VOLCARONA  ; e4
	const ICON_TYNAMO     ; e5
	const ICON_EELEKTRIK  ; e6
	const ICON_EELEKTROSS ; e7
	const ICON_BELDUM     ; e8
	const ICON_METANG     ; e9
	const ICON_METAGROSS  ; ea
	const ICON_SPHEAL     ; eb
	const ICON_SEALEO     ; ec
	const ICON_WALREIN    ; ed
	const ICON_SNORUNT    ; ee
	const ICON_GLALIE     ; ef
	const ICON_FROSLASS   ; f0
	const ICON_CRYOGONAL  ; f1
	const ICON_HORSEA     ; f2
	const ICON_SEADRA     ; f3
	const ICON_KINGDRA    ; f4
	const ICON_STUNFISK   ; f5
	const ICON_DRATINI    ; f6
	const ICON_DRAGONAIR  ; f7
	const ICON_DRAGONITE  ; f8
	const ICON_DEINO      ; f9
	const ICON_ZWEILOUS   ; fa
	const ICON_HYDREIGON  ; fb
	const ICON_GENESECT   ; fc
	const ICON_EGG        ; fd

; LoadMenuMonIcon.Jumptable indexes (see engine/gfx/mon_icons.asm)
	const_def
	const MONICON_PARTYMENU
	const MONICON_NAMINGSCREEN
	const MONICON_MOVES
	const MONICON_TRADE
	const MONICON_MOBILE1
	const MONICON_MOBILE2
	const MONICON_UNUSED
	
; party menu icon palettes
	const_def
	const PAL_ICON_RED    ; 0
	const PAL_ICON_BLUE   ; 1
	const PAL_ICON_GREEN  ; 2
	const PAL_ICON_BROWN  ; 3
	const PAL_ICON_PINK   ; 4
	const PAL_ICON_GREY   ; 5
	const PAL_ICON_TEAL   ; 6
	const PAL_ICON_PURPLE ; 7
