; mart types (see engine/items/mart.asm)
	const_def
	const MARTTYPE_STANDARD
	const MARTTYPE_BITTER
	const MARTTYPE_BARGAIN
	const MARTTYPE_PHARMACY
	const MARTTYPE_ROOFTOP
	const MARTTYPE_CAFE
	const MARTTYPE_MARKET

; Marts indexes (see data/items/marts.asm)
	const_def
	const MART_UNDERGROUND
	const MART_HUMILAU
	const MART_HUMILAU_DEX
	const MART_LACUNOSA
	const MART_LACUNOSA_DEX
	const MART_LENTIMAS
	const MART_NIMBASA
	const MART_NIMBASA_VITAMIN
	const MART_NIMBASA_BALL
	const MART_R4_NIMBASA_GATE
	const MART_CASTELIA_2F_1
	const MART_CASTELIA_2F_2
	const MART_CASTELIA_3F
	const MART_CASTELIA_4F
	const MART_ASPERTIA
	const MART_VIRBANK
	const MART_NACRENE
	const MART_NACRENE_CAFE
	const MART_STRIATON
	const MART_ACCUMULA
	const MART_DRIFTVEIL
	const MART_MERCHANT_1
	const MART_MERCHANT_2
	const MART_MISTRALTON
	const MART_OPELUCID
	const MART_ICIRRUS
	const MART_MALL_1
	const MART_MALL_2
	const MART_MALL_3
	const MART_MALL_4
	const MART_MALL_5
