; move ids
; indexes for:
; - Moves (see data/moves/moves.asm)
; - MoveNames (see data/moves/names.asm)
; - MoveDescriptions (see data/moves/descriptions.asm)
; - BattleAnimations (see data/moves/animations.asm)
	const_def
	const NO_MOVE      ; 00
	const VINE_WHIP    ; 01
	const RAZOR_LEAF   ; 02
	const SEED_BOMB    ; 03
	const LEAF_BLADE   ; 04
	const WOOD_HAMMER  ; 05
	const ABSORB       ; 06
	const MEGA_DRAIN   ; 07
	const GIGA_DRAIN   ; 08
	const MAGICAL_LEAF ; 09
	const ENERGY_BALL  ; 0a
	const PETAL_DANCE  ; 0b
	const SOLARBEAM    ; 0c
	const LEECH_SEED   ; 0d
	const STUN_SPORE   ; 0e
	const SLEEP_POWDER ; 0f
	const SPORE        ; 10
	const SYNTHESIS    ; 11
	const FLAME_WHEEL  ; 12
	const FIRE_FANG    ; 13
	const FIRE_PUNCH   ; 14
	const FLARE_BLITZ  ; 15
	const EMBER        ; 16
	const FIRE_SPIN    ; 17
	const LAVA_PLUME   ; 18
	const FLAMETHROWER ; 19
	const FIRE_BLAST   ; 1a
	const OVERHEAT     ; 1b
	const SUNNY_DAY    ; 1c
	const WILL_O_WISP  ; 1d
	const AQUA_JET     ; 1e
	const WATERFALL    ; 1f
	const AQUA_TAIL    ; 20
	const WATER_GUN    ; 21
	const BUBBLE       ; 22
	const BUBBLEBEAM   ; 23
	const WATER_PULSE  ; 24
	const SCALD        ; 25
	const SURF         ; 26
	const HYDRO_PUMP   ; 27
	const RAIN_DANCE   ; 28
	const SPARK        ; 29
	const THUNDER_FANG ; 2a
	const THUNDERPUNCH ; 2b
	const WILD_CHARGE  ; 2c
	const THUNDERSHOCK ; 2d
	const SHOCK_WAVE   ; 2e
	const DISCHARGE    ; 2f
	const THUNDERBOLT  ; 30
	const THUNDER      ; 31
	const ZAP_CANNON   ; 32
	const THUNDER_WAVE ; 33
	const ICE_SHARD    ; 34
	const ICE_FANG     ; 35
	const ICE_PUNCH    ; 36
	const ICICLE_CRASH ; 37
	const POWDER_SNOW  ; 38
	const ICY_WIND     ; 39
	const AURORA_BEAM  ; 3a
	const ICE_BEAM     ; 3b
	const BLIZZARD     ; 3c
	const MIST         ; 3d
	const HAZE         ; 3e
	const LEECH_LIFE   ; 3f
	const FURY_CUTTER  ; 40
	const PIN_MISSILE  ; 41
	const BUG_BITE     ; 42
	const X_SCISSOR    ; 43
	const MEGAHORN     ; 44
	const STRUGGLE_BUG ; 45
	const SIGNAL_BEAM  ; 46
	const BUG_BUZZ     ; 47
	const STRING_SHOT  ; 48
	const QUIVER_DANCE ; 49
	const POISON_STING ; 4a
	const POISON_FANG  ; 4b
	const CROSS_POISON ; 4c
	const GUNK_SHOT    ; 4d
	const ACID         ; 4e
	const VENOSHOCK    ; 4f
	const SLUDGE       ; 50
	const SLUDGE_BOMB  ; 51
	const ACID_ARMOR   ; 52
	const POISONPOWDER ; 53
	const POISON_GAS   ; 54
	const TOXIC        ; 55
	const COUNTER      ; 56
	const MACH_PUNCH   ; 57
	const KARATE_CHOP  ; 58
	const LOW_KICK     ; 59
	const DOUBLE_KICK  ; 5a
	const VITAL_THROW  ; 5b
	const DRAIN_PUNCH  ; 5c
	const REVERSAL     ; 5d
	const CROSS_CHOP   ; 5e
	const DYNAMICPUNCH ; 5f
	const HAMMER_ARM   ; 60
	const CLOSE_COMBAT ; 61
	const HI_JUMP_KICK ; 62
	const AURA_SPHERE  ; 63
	const FOCUS_BLAST  ; 64
	const DETECT       ; 65
	const BULK_UP      ; 66
	const PECK         ; 67
	const WING_ATTACK  ; 68
	const DRILL_PECK   ; 69
	const FLY          ; 6a
	const ACROBATICS   ; 6b
	const BRAVE_BIRD   ; 6c
	const GUST         ; 6d
	const AIR_CUTTER   ; 6e
	const AIR_SLASH    ; 6f
	const HURRICANE    ; 70
	const PSYCHO_CUT   ; 71
	const ZEN_HEADBUTT ; 72
	const CONFUSION    ; 73
	const PSYBEAM      ; 74
	const EXTRASENSORY ; 75
	const PSYSHOCK     ; 76
	const PSYCHIC_M    ; 77
	const DREAM_EATER  ; 78
	const MIRROR_COAT  ; 79
	const AGILITY      ; 7a
	const AMNESIA      ; 7b
	const REST         ; 7c
	const HYPNOSIS     ; 7d
	const REFLECT      ; 7e
	const LIGHT_SCREEN ; 7f
	const BARRIER      ; 80
	const CALM_MIND    ; 81
	const BULLDOZE     ; 82
	const MAGNITUDE    ; 83
	const DIG          ; 84
	const EARTHQUAKE   ; 85
	const MUD_SLAP     ; 86
	const MUD_SHOT     ; 87
	const EARTH_POWER  ; 88
	const SAND_ATTACK  ; 89
	const ROCK_THROW   ; 8a
	const ROLLOUT      ; 8b
	const ROCK_TOMB    ; 8c
	const ROCK_SLIDE   ; 8d
	const STONE_EDGE   ; 8e
	const ANCIENTPOWER ; 8f
	const POWER_GEM    ; 90
	const SANDSTORM    ; 91
	const LICK         ; 92
	const SHADOW_SNEAK ; 93
	const SHADOW_PUNCH ; 94
	const SHADOW_CLAW  ; 95
	const NIGHT_SHADE  ; 96
	const HEX          ; 97
	const SHADOW_BALL  ; 98
	const CONFUSE_RAY  ; 99
	const DESTINY_BOND ; 9a
	const CURSE        ; 9b
	const DRAGON_CLAW  ; 9c
	const OUTRAGE      ; 9d
	const DRAGON_RAGE  ; 9e
	const DRAGONBREATH ; 9f
	const DRAGON_PULSE ; a0
	const DRAGON_DANCE ; a1
	const PURSUIT      ; a2
	const THIEF        ; a3
	const BITE         ; a4
	const FAINT_ATTACK ; a5
	const NIGHT_SLASH  ; a6
	const CRUNCH       ; a7
	const SUCKER_PUNCH ; a8
	const DARK_PULSE   ; a9
	const HONE_CLAWS   ; aa
	const NASTY_PLOT   ; ab
	const BULLET_PUNCH ; ac
	const METAL_CLAW   ; ad
	const STEEL_WING   ; ae
	const IRON_HEAD    ; af
	const IRON_TAIL    ; b0
	const METEOR_MASH  ; b1
	const GEAR_GRIND   ; b2
	const MIRROR_SHOT  ; b3
	const FLASH_CANNON ; b4
	const IRON_DEFENSE ; b5
	const PLAY_ROUGH   ; b6
	const FAIRY_WIND   ; b7
	const DRAININGKISS ; b8
	const DAZZLINGLEAM ; b9
	const MOONBLAST    ; ba
	const CHARM        ; bb
	const SWEET_KISS   ; bc
	const MOONLIGHT    ; bd
	const TACKLE       ; be
	const TAKE_DOWN    ; bf
	const DOUBLE_EDGE  ; c0
	const BODY_SLAM    ; c1
	const SCRATCH      ; c2
	const SLASH        ; c3
	const SUPER_FANG   ; c4
	const CUT          ; c5
	const STRENGTH     ; c6
	const VICEGRIP     ; c7
	const QUICK_ATTACK ; c8
	const WRAP         ; c9
	const FURY_ATTACK  ; ca
	const FURY_SWIPES  ; cb
	const DOUBLESLAP   ; cc
	const DIZZY_PUNCH  ; cd
	const HEADBUTT     ; ce
	const SELFDESTRUCT ; cf
	const EXPLOSION    ; d0
	const RETURN       ; d1
	const EXTREMESPEED ; d2
	const FLAIL        ; d3
	const GIGA_IMPACT  ; d4
	const SWIFT        ; d5
	const SONICBOOM    ; d6
	const TRI_ATTACK   ; d7
	const HIDDEN_POWER ; d8
	const HYPER_VOICE  ; d9
	const HYPER_BEAM   ; da
	const GROWL        ; db
	const GROWTH       ; dc
	const LEER         ; dd
	const TAIL_WHIP    ; de
	const DEFENSE_CURL ; df
	const HARDEN       ; e0
	const SMOKESCREEN  ; e1
	const DOUBLE_TEAM  ; e2
	const MINIMIZE     ; e3
	const SCREECH      ; e4
	const GLARE        ; e5
	const SING         ; e6
	const SUPERSONIC   ; e7
	const DISABLE      ; e8
	const RECOVER      ; e9
	const WHIRLWIND    ; ea
	const ROAR         ; eb
	const FOCUS_ENERGY ; ec
	const SWORDS_DANCE ; ed
	const METRONOME    ; ee
	const TRANSFORM    ; ef
	const MEAN_LOOK    ; f0
	const SCARY_FACE   ; f1
	const SAFEGUARD    ; f2
	const BELLY_DRUM   ; f3
	const SWAGGER      ; f4
	const SWEET_SCENT  ; f5
	const PAIN_SPLIT   ; f6
	const PERISH_SONG  ; f7
	const PSYCH_UP     ; f8
	const PROTECT      ; f9
	const ENDURE       ; fa
	const ENCORE       ; fb
	const LOCK_ON      ; fc
	const FORESIGHT    ; fd
	const ATTRACT      ; fe
	const STRUGGLE     ; ff
NUM_ATTACKS EQU const_value + -1

; Battle animations use the same constants as the moves up to this point
	const ANIM_SWEET_SCENT_2     ; ff
	const ANIM_THROW_POKE_BALL   ; 100
	const ANIM_SEND_OUT_MON      ; 101
	const ANIM_RETURN_MON        ; 102
	const ANIM_CONFUSED          ; 103
	const ANIM_SLP               ; 104
	const ANIM_BRN               ; 105
	const ANIM_PSN               ; 106
	const ANIM_SAP               ; 107
	const ANIM_FRZ               ; 108
	const ANIM_PAR               ; 109
	const ANIM_IN_LOVE           ; 10a
	const ANIM_IN_SANDSTORM      ; 10b
	const ANIM_IN_NIGHTMARE      ; 10c
	const ANIM_IN_WHIRLPOOL      ; 10d
; battle anims
	const ANIM_MISS              ; 10e
	const ANIM_ENEMY_DAMAGE      ; 10f
	const ANIM_ENEMY_STAT_DOWN   ; 110
	const ANIM_PLAYER_STAT_DOWN  ; 111
	const ANIM_PLAYER_DAMAGE     ; 112
	const ANIM_WOBBLE            ; 113
	const ANIM_SHAKE             ; 114
	const ANIM_HIT_CONFUSION     ; 115

; wNumHits uses offsets from ANIM_MISS
	const_def
	const BATTLEANIM_NONE
	const BATTLEANIM_ENEMY_DAMAGE
	const BATTLEANIM_ENEMY_STAT_DOWN
	const BATTLEANIM_PLAYER_STAT_DOWN
	const BATTLEANIM_PLAYER_DAMAGE
	const BATTLEANIM_WOBBLE
	const BATTLEANIM_SHAKE
	const BATTLEANIM_HIT_CONFUSION
