; See song sections in audio.asm.

Music:
; entries correspond to MUSIC_* constants
	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_MagnetTrain
	dba Music_PokemonCenter
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookCyclist
	dba Music_HealPokemon
	dba Music_ShowMeAround
	dba Music_GameCorner
	dba Music_KalosBicycle
	dba Music_HallOfFame
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_Gym
	dba Music_ProfOaksPokemonTalk
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_Surf
	dba Music_Evolution
	dba Music_Credits
	dba Music_LookAceTrainer
	dba Music_JohtoWildBattle
	dba Music_UnovaTrainerBattle
	dba Music_JohtoGymBattle
	dba Music_LastPokemon
	dba Music_RivalBattle
	dba Music_RocketBattle
	dba Music_LookYoungster
	dba Music_LookLady
	dba Music_LookPlasma
	dba Music_LookPsychic
	dba Music_LookScientist
	dba Music_PokemonChannel
	dba Music_PokeFluteChannel
	dba Music_JohtoWildBattleNight
	dba Music_RuinsOfAlphRadio
	dba Music_SuccessfulCapture
	dba Music_Mom
	dba Music_BlackCity
	dba Music_PokemonLullaby
	dba Music_PokemonMarch
	dba Music_MainMenu
	dba Music_Printer
	dba Music_PostCredits
	dba Music_LookTwins
	dba Music_MobileCenter
	dba Music_CelestialTower_NoIntro
	dba Music_MobileAdapterMenu
	dba Music_HumilauCity
	dba Music_LacunosaTown
	dba Music_UnovaRoute2
	dba Music_BrendanEncounter
	dba Music_LentimasTown
	dba Music_ScaryHouse
	dba Music_PetalburgWoods
	dba Music_UnovaRoute4
	dba Music_NimbasaCity
	dba Music_UnovaRoute1
	dba Music_CasteliaCity
	dba Music_RoadToReversalMountain
	dba Music_AccumulaTown
	dba Music_AspertiaCity
	dba Music_OldaleTown
	dba Music_JubilifeCity
	dba Music_KalosPowerPlant
	dba Music_LookZinnia
	dba Music_Route10
	dba Music_SkyarrowBridge
	dba Music_StriatonCity
	dba Music_UnovaCave
	dba Music_UnovaRoute12
	dba Music_DriftveilCity
	dba Music_UnovaRoute6
	dba Music_CasteliaSewers
	dba Music_MistraltonCity
	dba Music_IcirrusCity
	dba Music_Mart
	dba Music_UnovaEliteFourBattle
	dba Music_BWPokemonLeague
	dba Music_AnvilleTown
	dba Music_LookRoughneck
	dba Music_LookGentleman
	dba Music_LookPokefan
	dba Music_LookWorker
	dba Music_BattleGhetsis
	dba Music_NuvemaTown
	dba Music_RocketHideout
