	const_def 2 ; object constants
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_4_UPPER_DUMMY
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_4_LOWER_DUMMY
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_5_UPPER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_5_LOWER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_6_UPPER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_6_LOWER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_7_UPPER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_7_LOWER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_8_UPPER
	const VICTORYROADENTRANCESOUTHLEFT_BADGE_8_LOWER

VictoryRoadEntranceSouthLeft_MapScripts:
	db 0 ; scene scripts

	db 0 ; callbacks

VictoryRoadEntranceSouthLeft_MapEvents:
	db 0, 0 ; filler

	db 0 ; warp events

	db 0 ; coord events
	
	db 0 ; bg events
	
	db 10 ; object events
	object_event 30, 02, SPRITE_BADGE_4, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 30, 06, SPRITE_BADGE_4, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event 26, 02, SPRITE_BADGE_5, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 26, 06, SPRITE_BADGE_5, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event 22, 02, SPRITE_BADGE_6, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 22, 06, SPRITE_BADGE_6, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event 18, 02, SPRITE_BADGE_7, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 18, 06, SPRITE_BADGE_7, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event 14, 02, SPRITE_BADGE_8, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 14, 06, SPRITE_BADGE_8, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	