	const_def 2 ; object constants
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_1_UPPER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_1_LOWER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_2_UPPER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_2_LOWER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_3_UPPER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_3_LOWER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_4_UPPER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_4_LOWER
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_5_UPPER_DUMMY
	const VICTORYROADENTRANCESOUTHRIGHT_BADGE_5_LOWER_DUMMY

VictoryRoadEntranceSouthRight_MapScripts:
	db 0 ; scene scripts
	
	db 1 ; callbacks
	callback MAPCALLBACK_NEWMAP, .Clear_R23_Flag
	
.Clear_R23_Flag:
	clearevent EVENT_R23_WEST_UPPER_LEVEL
	return

VictoryRoadEntranceSouthRight_MapEvents:
	db 0, 0 ; filler

	db 2 ; warp events
	warp_event 18, 11, R_23_WEST, 7
	warp_event 19, 11, R_23_WEST, 8

	db 0 ; coord events
	
	db 0 ; bg events
	
	db 10 ; object events
	object_event 14,  2, SPRITE_BADGE_1, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 14,  6, SPRITE_BADGE_1, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event 10,  2, SPRITE_BADGE_2, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event 10,  6, SPRITE_BADGE_2, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event  6,  2, SPRITE_BADGE_3, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event  6,  6, SPRITE_BADGE_3, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event  2,  2, SPRITE_BADGE_4, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event  2,  6, SPRITE_BADGE_4, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	object_event -2,  2, SPRITE_BADGE_5, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_ROCK, OBJECTTYPE_3, 0, 0, -1
	object_event -2,  6, SPRITE_BADGE_5, SPRITEMOVEDATA_BADGE, 0, 0, -1, -1, PAL_NPC_TREE, OBJECTTYPE_3, 0, 0, -1
	